export default strings = {
  title: 'The Random User ',
  favourites: 'Favourites',
  app_name: 'Track App',
  details: 'Details',
  gender: 'Gender',
  country: 'Country',
  please_turn_on: 'Please turn ON your data or wifi',
  no_internet_connection: 'No Internet Connection',
  please_check_your_internet: 'Please check your internet connection',
  try_again: 'Try Again',
  no_user_to_show: 'No user to show.',
  no_fav_to_show: 'No favourite User to show.',
  search_by: 'Search',
};
